# Generated by Django 3.2 on 2022-02-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('sub_title', models.CharField(max_length=64)),
                ('image', models.FileField(max_length=128, upload_to='product_image')),
                ('detail', models.FileField(max_length=128, upload_to='product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.users')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.users'),
        ),
        migrations.CreateModel(
            name='GoodDetailImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods')),
            ],
        ),
    ]
