# Generated by Django 3.2 on 2022-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220220_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='product_detail'),
        ),
    ]
