# Generated by Django 3.2 on 2022-02-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_goods_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddetailimages',
            name='product',
        ),
        migrations.AddField(
            model_name='goods',
            name='small_image',
            field=models.ManyToManyField(to='app01.GoodDetailImages'),
        ),
    ]
