# Generated by Django 3.2 on 2022-02-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20220221_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddetailimages',
            name='image_url',
            field=models.FileField(max_length=128, upload_to='product_small_images'),
        ),
    ]
