# Generated by Django 3.2 on 2022-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='user_head'),
        ),
    ]
