# Generated by Django 3.2 on 2022-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_users_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.ManyToManyField(to='app01.Goods'),
        ),
    ]
