# Generated by Django 3.2 on 2022-03-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20220301_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cart',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.users')),
            ],
        ),
    ]
